// Code generated by protoc-gen-go. DO NOT EDIT.
// source: event-service.proto

package v1

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	timestamp "github.com/golang/protobuf/ptypes/timestamp"
	grpc "google.golang.org/grpc"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Event struct {
	Id                   int64                `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Description          string               `protobuf:"bytes,2,opt,name=description,proto3" json:"description,omitempty"`
	UpVotes              int64                `protobuf:"varint,3,opt,name=up_votes,json=upVotes,proto3" json:"up_votes,omitempty"`
	DownVotes            int64                `protobuf:"varint,4,opt,name=down_votes,json=downVotes,proto3" json:"down_votes,omitempty"`
	UpdatedDate          *timestamp.Timestamp `protobuf:"bytes,5,opt,name=updated_date,json=updatedDate,proto3" json:"updated_date,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *Event) Reset()         { *m = Event{} }
func (m *Event) String() string { return proto.CompactTextString(m) }
func (*Event) ProtoMessage()    {}
func (*Event) Descriptor() ([]byte, []int) {
	return fileDescriptor_03a7d11584ae62cc, []int{0}
}

func (m *Event) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Event.Unmarshal(m, b)
}
func (m *Event) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Event.Marshal(b, m, deterministic)
}
func (m *Event) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Event.Merge(m, src)
}
func (m *Event) XXX_Size() int {
	return xxx_messageInfo_Event.Size(m)
}
func (m *Event) XXX_DiscardUnknown() {
	xxx_messageInfo_Event.DiscardUnknown(m)
}

var xxx_messageInfo_Event proto.InternalMessageInfo

func (m *Event) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *Event) GetDescription() string {
	if m != nil {
		return m.Description
	}
	return ""
}

func (m *Event) GetUpVotes() int64 {
	if m != nil {
		return m.UpVotes
	}
	return 0
}

func (m *Event) GetDownVotes() int64 {
	if m != nil {
		return m.DownVotes
	}
	return 0
}

func (m *Event) GetUpdatedDate() *timestamp.Timestamp {
	if m != nil {
		return m.UpdatedDate
	}
	return nil
}

type CreateRequest struct {
	Api                  string   `protobuf:"bytes,1,opt,name=api,proto3" json:"api,omitempty"`
	Event                *Event   `protobuf:"bytes,2,opt,name=event,proto3" json:"event,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateRequest) Reset()         { *m = CreateRequest{} }
func (m *CreateRequest) String() string { return proto.CompactTextString(m) }
func (*CreateRequest) ProtoMessage()    {}
func (*CreateRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_03a7d11584ae62cc, []int{1}
}

func (m *CreateRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateRequest.Unmarshal(m, b)
}
func (m *CreateRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateRequest.Marshal(b, m, deterministic)
}
func (m *CreateRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateRequest.Merge(m, src)
}
func (m *CreateRequest) XXX_Size() int {
	return xxx_messageInfo_CreateRequest.Size(m)
}
func (m *CreateRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CreateRequest proto.InternalMessageInfo

func (m *CreateRequest) GetApi() string {
	if m != nil {
		return m.Api
	}
	return ""
}

func (m *CreateRequest) GetEvent() *Event {
	if m != nil {
		return m.Event
	}
	return nil
}

type CreateResponse struct {
	Api                  string   `protobuf:"bytes,1,opt,name=api,proto3" json:"api,omitempty"`
	Id                   int64    `protobuf:"varint,2,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateResponse) Reset()         { *m = CreateResponse{} }
func (m *CreateResponse) String() string { return proto.CompactTextString(m) }
func (*CreateResponse) ProtoMessage()    {}
func (*CreateResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_03a7d11584ae62cc, []int{2}
}

func (m *CreateResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateResponse.Unmarshal(m, b)
}
func (m *CreateResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateResponse.Marshal(b, m, deterministic)
}
func (m *CreateResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateResponse.Merge(m, src)
}
func (m *CreateResponse) XXX_Size() int {
	return xxx_messageInfo_CreateResponse.Size(m)
}
func (m *CreateResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateResponse.DiscardUnknown(m)
}

var xxx_messageInfo_CreateResponse proto.InternalMessageInfo

func (m *CreateResponse) GetApi() string {
	if m != nil {
		return m.Api
	}
	return ""
}

func (m *CreateResponse) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func init() {
	proto.RegisterType((*Event)(nil), "v1.Event")
	proto.RegisterType((*CreateRequest)(nil), "v1.CreateRequest")
	proto.RegisterType((*CreateResponse)(nil), "v1.CreateResponse")
}

func init() { proto.RegisterFile("event-service.proto", fileDescriptor_03a7d11584ae62cc) }

var fileDescriptor_03a7d11584ae62cc = []byte{
	// 288 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x6c, 0x90, 0xdf, 0x4a, 0xc3, 0x30,
	0x14, 0xc6, 0x69, 0x6b, 0xa7, 0x3d, 0x9d, 0x43, 0xe3, 0x4d, 0x2d, 0xc8, 0x4a, 0xaf, 0x7a, 0x63,
	0xca, 0xea, 0xb5, 0x08, 0xfe, 0x79, 0x81, 0x28, 0xde, 0x8e, 0x6e, 0x39, 0x8e, 0x80, 0x6b, 0x62,
	0x93, 0xd6, 0xf7, 0xf2, 0x09, 0x25, 0xc9, 0x0a, 0x13, 0xbc, 0x09, 0xc9, 0x77, 0xce, 0xf9, 0xf2,
	0x3b, 0x1f, 0x5c, 0xe1, 0x88, 0x9d, 0xb9, 0xd5, 0xd8, 0x8f, 0x62, 0x8b, 0x54, 0xf5, 0xd2, 0x48,
	0x12, 0x8e, 0xab, 0x7c, 0xb9, 0x93, 0x72, 0xf7, 0x89, 0xb5, 0x53, 0x36, 0xc3, 0x47, 0x6d, 0xc4,
	0x1e, 0xb5, 0x69, 0xf7, 0xca, 0x37, 0x95, 0x3f, 0x01, 0xc4, 0x2f, 0x76, 0x98, 0x2c, 0x20, 0x14,
	0x3c, 0x0b, 0x8a, 0xa0, 0x8a, 0x58, 0x28, 0x38, 0x29, 0x20, 0xe5, 0xa8, 0xb7, 0xbd, 0x50, 0x46,
	0xc8, 0x2e, 0x0b, 0x8b, 0xa0, 0x4a, 0xd8, 0xb1, 0x44, 0xae, 0xe1, 0x6c, 0x50, 0xeb, 0x51, 0x1a,
	0xd4, 0x59, 0xe4, 0xe6, 0x4e, 0x07, 0xf5, 0x6e, 0x9f, 0xe4, 0x06, 0x80, 0xcb, 0xef, 0xee, 0x50,
	0x3c, 0x71, 0xc5, 0xc4, 0x2a, 0xbe, 0x7c, 0x0f, 0xf3, 0x41, 0xf1, 0xd6, 0x20, 0x5f, 0xdb, 0x33,
	0x8b, 0x8b, 0xa0, 0x4a, 0x9b, 0x9c, 0x7a, 0x5a, 0x3a, 0xd1, 0xd2, 0xb7, 0x89, 0x96, 0xa5, 0x87,
	0xfe, 0xe7, 0xd6, 0x60, 0xf9, 0x08, 0xe7, 0x4f, 0x3d, 0xb6, 0x06, 0x19, 0x7e, 0x0d, 0xa8, 0x0d,
	0xb9, 0x80, 0xa8, 0x55, 0xc2, 0xc1, 0x27, 0xcc, 0x5e, 0xc9, 0x12, 0x62, 0x97, 0x89, 0xe3, 0x4e,
	0x9b, 0x84, 0x8e, 0x2b, 0xea, 0xf6, 0x64, 0x5e, 0x2f, 0x1b, 0x58, 0x4c, 0x1e, 0x5a, 0xc9, 0x4e,
	0xe3, 0x3f, 0x26, 0x3e, 0x92, 0x70, 0x8a, 0xa4, 0x79, 0x80, 0xb9, 0xf3, 0x78, 0xf5, 0x39, 0x93,
	0x1a, 0x66, 0xde, 0x83, 0x5c, 0x5a, 0xff, 0x3f, 0x4c, 0x39, 0x39, 0x96, 0xfc, 0x17, 0x9b, 0x99,
	0xdb, 0xec, 0xee, 0x37, 0x00, 0x00, 0xff, 0xff, 0xc8, 0xae, 0xd0, 0x40, 0xb0, 0x01, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// EventServiceClient is the client API for EventService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type EventServiceClient interface {
	Create(ctx context.Context, in *CreateRequest, opts ...grpc.CallOption) (*CreateResponse, error)
}

type eventServiceClient struct {
	cc *grpc.ClientConn
}

func NewEventServiceClient(cc *grpc.ClientConn) EventServiceClient {
	return &eventServiceClient{cc}
}

func (c *eventServiceClient) Create(ctx context.Context, in *CreateRequest, opts ...grpc.CallOption) (*CreateResponse, error) {
	out := new(CreateResponse)
	err := c.cc.Invoke(ctx, "/v1.EventService/Create", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// EventServiceServer is the server API for EventService service.
type EventServiceServer interface {
	Create(context.Context, *CreateRequest) (*CreateResponse, error)
}

func RegisterEventServiceServer(s *grpc.Server, srv EventServiceServer) {
	s.RegisterService(&_EventService_serviceDesc, srv)
}

func _EventService_Create_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EventServiceServer).Create(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/v1.EventService/Create",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EventServiceServer).Create(ctx, req.(*CreateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _EventService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "v1.EventService",
	HandlerType: (*EventServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Create",
			Handler:    _EventService_Create_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "event-service.proto",
}
